image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm start
    - ls

deploy:
  stage: deploy
  script:
    - ls
    # - systemctl status nginx
    # - systemctl restart nginx