image: node:20

stages:
  - build
  - deploy

variables:
  NODE_ENV: production

build:
  stage: build
  scripts:
    - npm install
    - npm run build
    - ls

deploy:
  stage: deploy
  scripts:
    - hello world