image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build


deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh andre@172.16.100.46
    - scp -r ./build/* andre@172.16.100.46
    - ssh andre@172.16.100.46 "sudo systemctl status nginx"
    - ssh andre@172.16.100.46 "sudo systemctl restart nginx"

