image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - ls

deploy:
  stage: deploy
  script:
    - sudo systemctl status nginx
    - sudo systemctl restart nginx