image: node:20

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build 
    - ls
  artifacts:
    paths:
      - build/


deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update && apt-get install -y sshpass
    - ls
    - sshpass -p "$SSH_PASS" ssh andre@172.16.100.46 "mkdir -p /app"
    - sshpass -p "$SSH_PASS" scp -r build/* andre@172.16.100.46:/app
    #- ssh andre@172.16.100.46 "sudo systemctl status nginx"
    #- ssh andre@172.16.100.46 "sudo systemctl restart nginx"

